// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PriceRack.DataAccess.DBContexts;

#nullable disable

namespace PriceRack.DataAccess.Migrations
{
    [DbContext(typeof(PriceContext))]
    [Migration("20230429095327_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("PriceRack.DataAccess.Entities.Price", b =>
                {
                    b.Property<string>("Instrument")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Instrument", "Time");

                    b.ToTable("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
